# This is a basic workflow to help you get started with Actions

name: CI


on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./Signal-Android

    steps:
    - uses: actions/checkout@v2

    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1

#     - name: Remove Android 31 (S)
#       run: $ANDROID_HOME/tools/bin/sdkmanager --uninstall "platforms;android-31"
#       working-directory: ${{env.working-directory}}
      
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      working-directory: ${{env.working-directory}}

    - name: Build with Gradle
      run: ./gradlew qa
      working-directory: ${{env.working-directory}}

    - name: Archive reports for failed build
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: reports
        path: '*/build/reports'
